-- ============================================
-- User profiles: tag + hourly message summary
-- ============================================

CREATE TABLE IF NOT EXISTS user_profiles (
  chat_id INTEGER NOT NULL,
  uid INTEGER NOT NULL,
  username TEXT NOT NULL DEFAULT '',
  full_name TEXT NOT NULL DEFAULT '',
  -- Latest known Telegram tag (Bot API 9.5+)
  sender_tag TEXT,
  -- Hourly summary prompt generated by Qwen3.6+
  profile_prompt TEXT,
  -- Raw recent message log for next summarization cycle (JSON array of strings)
  pending_messages TEXT NOT NULL DEFAULT '[]',
  updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
  PRIMARY KEY (chat_id, uid)
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_chat ON user_profiles(chat_id);
